export type PostStatus = 'growing' | 'harvested'
export type PostItemStatus = 'ongoing' | 'fulfilled' | 'archived'
export type PostType = 'supply' | 'demand'
export type PostTimeSlot = 'morning' | 'afternoon' | 'evening'
export type PostPriceFlag = 'Low' | 'Fair' | 'High'
